# Generated by Django 4.0.4 on 2022-05-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_employee',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_on_time',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='job',
            field=models.CharField(choices=[('Engineer', 'エンジニア'), ('Designer', 'デザイナー')], max_length=10, null=True),
        ),
    ]
