# Generated by Django 4.0.4 on 2022-05-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_currency', '0002_alter_member_is_employee_alter_member_is_on_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='job',
            field=models.CharField(choices=[('Engineer', 'エンジニア'), ('Designer', 'デザイナー')], default='Engineer', max_length=10),
        ),
    ]
