# Generated by Django 4.0.4 on 2022-05-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_currency', '0005_alter_member_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
