# Generated by Django 4.0.4 on 2022-05-16 19:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_currency', '0006_member_is_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('primary', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField()),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_of_quiz', to='manage_currency.answer')),
            ],
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=140)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_of_option', to='manage_currency.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizes', models.ManyToManyField(related_name='quizes', to='manage_currency.quiz')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_currency.team')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='correct_option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_currency.quizoption'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_of_answer', to='manage_currency.quiz'),
        ),
    ]
