# Generated by Django 4.0.4 on 2022-05-19 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_currency', '0010_team_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='rank',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='primary',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
