# Generated by Django 4.0.4 on 2022-05-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_currency', '0011_remove_team_rank_alter_quiz_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedquiz',
            name='selected_choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manage_currency.quizoption'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_of_quiz', to='manage_currency.answer'),
        ),
    ]
