# Generated by Django 4.0.4 on 2022-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_currency', '0015_alter_finishedquiz_selected_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_canceled',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
