# Generated by Django 4.0.4 on 2022-05-22 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_currency', '0018_purchase_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_cash', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_current', models.BooleanField()),
            ],
        ),
    ]
