# Generated by Django 4.0.4 on 2022-05-22 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_currency', '0019_allcash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcash',
            name='all_cash',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
