# Generated by Django 4.0.4 on 2022-05-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_currency', '0021_remove_allcash_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcash',
            name='is_current',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
