# Generated by Django 4.0.4 on 2022-05-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_currency', '0022_allcash_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcash',
            name='is_current',
        ),
    ]
